spring:
  application:
    name: dev
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000          # 1 ngày (ms)
      refresh-token:
        expiration: 604800000       # 7 ngày (ms)